### ISSUE TITLE
[Bug] QWebSocketPrivate::processHandshake: Unhandled http status code: 200 (OK)

### ISSUE THREAD

**Issue by DemianTinkiel** [korapp/plasma-homeassistant#50]
**Describe the bug**
Cannot log into my HA instance: QWebSocketPrivate::processHandshake: Unhandled http status code: 200 (OK). 
**To Reproduce**
1. Add credentials and token
2. Click on apply
3. click on items

**Expected behavior**
See entities of my HA instance
**Screenshots**
N/A
**Desktop (please complete the following information):**
 - Distribution: Nobara Linux 39
 - KDE Plasma 6.0.5
 - KDE Frameworks 6.2.0
**Additional context**
Using https. Using self-signed CA which signs the cert for homeassistant. Root CA added to my truststore. See https://www.devdungeon.com/content/how-add-trusted-ca-certificate-centosfedora

**Comment by korapp** [comment]
For some reason the server returns HTTP 200 response instead of WebSocket 101. It looks like a configuration issue, the question is which one.

1. Are you using a relatively recent version of Home Assistant?
2. Does the URL in the plasmoid configuration starts with `https://` and end with the port number (required only if it's other than 443)?
3. What is the result of executing
    ```
   curl -H "Connection: Upgrade" -H "Upgrade: websocket" -H "Sec-WebSocket-Version: 13" -H "Sec-WebSocket-Key: `openssl rand -base64 16`" -sSv --http1.1 "https://YOUR_HA_URL/api/websocket"
    ```
